networks:
  semantic_network:
    driver: bridge
services:
  python-semantic-matcher_1:
    image: local/python-semantic-matcher
    build:
      context: https://github.com/s-heppner/python-semantic-matcher.git
    healthcheck:
      interval: 10s
      retries: 5
      test: CMD curl -f http://python-semantic-matcher_1:8000
      timeout: 5s
    networks:
    - semantic_network
    ports:
    - 8000:8010
  python-semantic-matcher_2:
    image: local/python-semantic-matcher
    build:
      context: https://github.com/s-heppner/python-semantic-matcher.git
    healthcheck:
      interval: 10s
      retries: 5
      test: CMD curl -f http://python-semantic-matcher_2:8000
      timeout: 5s
    networks:
    - semantic_network
    ports:
    - 8001:8011
  python-semantic-matcher_3:
    image: local/python-semantic-matcher
    build:
      context: https://github.com/s-heppner/python-semantic-matcher.git
    healthcheck:
      interval: 10s
      retries: 5
      test: CMD curl -f http://python-semantic-matcher_3:8000
      timeout: 5s
    networks:
    - semantic_network
    ports:
    - 8002:8012
  python-semantic-matcher_4:
    build:
      context: https://github.com/s-heppner/python-semantic-matcher.git
    healthcheck:
      interval: 10s
      retries: 5
      test: CMD curl -f http://python-semantic-matcher_4:8000
      timeout: 5s
    networks:
    - semantic_network
    ports:
    - 8003:8013
  semantic_id_resolver:
    image: local/semantic_id_resolver
    build:
      context: https://github.com/s-heppner/semantic_id_resolver.git
    depends_on:
    - python-semantic-matcher_1
    - python-semantic-matcher_2
    - python-semantic-matcher_3
    - python-semantic-matcher_4
    networks:
    - semantic_network
    ports:
    - 8125:8015
  test-semantic-matcher:
    build:
      context: .
    depends_on:
    - python-semantic-matcher_1
    - python-semantic-matcher_2
    - python-semantic-matcher_3
    - python-semantic-matcher_4
    networks:
    - semantic_network
    ports:
    - 8100:8019
    volumes:
    - ./data:/app/data
    - ../../../main:/app/main
    - ../../../util:/app/util
    - ../../../model:/app/model
version: '3.8'
